# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d2a9ab3d677f4d4fe69f7f6e121fa2223e0f848221abe9dfbdab494113c1b76e47a63e23e7c9facaa5f7a33b8de2d42df733ddd2b016ce46ea4a5c15bbf8394

test:
  secret_key_base: 33eee05e4443ef3dbbac467ff8386dd314dcf02987d804fd015dcd54d5093df28a444a3ceb4ba8884c8d5b199236e3459dc82f0d4604e7a869c01ca0a3b659de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
